format = """
$user\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$battery\
$c\
$lua\
$node.js\
$python\
$jobs\
$time\
$line_break\
$status\
$cmd_duration\
$character\
"""

[directory]
truncation_length = 5
truncation_symbol = '…/'
style = 'bold cyan'
repo_root_style = 'bold purple'

[cmd_duration]
min_time = 4_000
show_milliseconds = true

[git_metrics]
disabled = false

[status]
disabled = false

[time]
disabled = false
format = '[ \[$time\]]($style) '
time_format = '%k:%M'
style = 'red'

[[battery.display]]
threshold = 30
style = 'bold red'


